import XCTest
import Foundation
@testable import MomijCore

/// Parity tests against the evprtr Python verify pipeline.
/// Expected values were generated by running
/// `compositor.verify` (find_repetition / detectors) on the same
/// fixtures with the venv interpreter; they are frozen here.
final class ResponseVerifyTests: XCTestCase {
    private let tco = ToolMarkup.callOpen          // markup open marker
    private let tcc = ToolMarkup.callClose         // markup close tag

    private func block(_ body: String) -> String {
        tco + "\n" + body + "\n" + tcc
    }

    // MARK: repetition.py

    func testFindRepetitionHealthy() {
        let text = "Sure. Here are the main entry points in this repository and what they do."
        XCTAssertNil(ResponseVerify.findRepetition(text))
        XCTAssertNil(ResponseVerify.findRepetition("tiny"))  // < 32 chars
    }

    func testFindRepetitionCharMotif() {
        // "processing complete: " + 20x "tr" + " end"
        let motif = String(repeating: "tr", count: 20)
        let text = "processing complete: " + motif + " end"
        let hit = ResponseVerify.findRepetition(text)
        XCTAssertEqual(hit?.kind, "char_motif")
        XCTAssertEqual(hit?.onset, 21)
        XCTAssertEqual(hit?.detail["motif"] as? String, "tr")
        XCTAssertEqual(hit?.detail["span"] as? Int, 40)
        XCTAssertEqual(ResponseVerify.truncateBeforeRepetition(text), "processing complete:")
    }

    func testFindRepetitionCharMotifWordRunCase() {
        // "agent" x10 with single spaces: the contiguous " agent" unit is
        // itself a char motif and its onset beats the word-run onset.
        let text = "let me think about this " + String(repeating: "agent ", count: 10) + "and continue."
        let hit = ResponseVerify.findRepetition(text)
        XCTAssertEqual(hit?.kind, "char_motif")
        XCTAssertEqual(hit?.onset, 23)
        XCTAssertEqual(hit?.detail["motif"] as? String, " agent")
        XCTAssertEqual(hit?.detail["span"] as? Int, 60)
        XCTAssertEqual(ResponseVerify.truncateBeforeRepetition(text), "let me think about this")
    }

    func testFindRepetitionWordRunSeparators() {
        // 8 identical tokens with alternating separator widths defeat the
        // contiguous char motif, so word_run wins. (Python oracle: onset 27.)
        let text = "start of the analysis here beta  beta beta  beta beta  beta beta  beta"
            + " and the conclusion follows now"
        let hit = ResponseVerify.findRepetition(text)
        XCTAssertEqual(hit?.kind, "word_run")
        XCTAssertEqual(hit?.onset, 27)
        XCTAssertEqual(hit?.detail["token"] as? String, "beta")
        XCTAssertEqual(hit?.detail["run"] as? Int, 8)
        XCTAssertEqual(ResponseVerify.truncateBeforeRepetition(text), "start of the analysis here")
    }

    func testFindRepetitionNgramRun() {
        // 7 identical tokens (5 identical 3-grams, total words >= 15):
        // ngram_run fires; word_run does not (needs 8).
        let text = "start of the analysis here alpha  alpha alpha  alpha alpha  alpha alpha"
            + " and the conclusion follows now"
        let hit = ResponseVerify.findRepetition(text)
        XCTAssertEqual(hit?.kind, "ngram_run")
        XCTAssertEqual(hit?.onset, 27)
        XCTAssertEqual(hit?.detail["ngram"] as? String, "alpha alpha alpha")
        XCTAssertEqual(hit?.detail["run"] as? Int, 5)
        XCTAssertEqual(hit?.detail["n"] as? Int, 3)
        XCTAssertEqual(ResponseVerify.truncateBeforeRepetition(text), "start of the analysis here")
    }

    func testFindRepetitionNoFalsePositiveOnReasoningBlob() {
        // Period-4 phrase repetition is below every threshold (evprtr: null).
        let text = "Step by step analysis. " + String(repeating: "therefore the result ", count: 6) + "concludes."
        XCTAssertNil(ResponseVerify.findRepetition(text))
    }

    func testRepetitionShortGuard() {
        XCTAssertNil(ResponseVerify.findRepetition("short text under limit"))
    }

    // MARK: thin content

    func testThinContentColon() {
        let hit = ResponseVerify.thinContent(.init(content: "Here are the files in the directory:"))
        XCTAssertEqual(hit?.policyId, ResponseVerify.thinContentId)
        XCTAssertEqual(hit?.kind, "thin_content")
        XCTAssertEqual(hit?.field, "content")
        XCTAssertEqual(hit?.onset, 0)
        XCTAssertEqual(hit?.detail["len"] as? Int, 36)
    }

    func testThinContentBulletsPass() {
        let hit = ResponseVerify.thinContent(
            .init(content: "Here are the files in the directory:\n- a.txt\n- b.txt"))
        XCTAssertNil(hit)
        // Healthy sentence: not colon-terminated.
        XCTAssertNil(ResponseVerify.thinContent(
            .init(content: "The command completed successfully without errors.")))
    }

    // MARK: pseudo tool markup

    func testPseudoToolMarkupInContent() {
        let content = "I will list files.\n\n" + block("{\"name\": \"ls\", \"arguments\": {\"path\": \"/tmp\"}}")
        let hit = ResponseVerify.pseudoToolCallInContent(.init(content: content))
        XCTAssertEqual(hit?.policyId, ResponseVerify.pseudoToolMarkupId)
        XCTAssertEqual(hit?.kind, "pseudo_tool_markup")
        XCTAssertEqual(hit?.field, "content")
        XCTAssertEqual(hit?.onset, 20)
        XCTAssertEqual(hit?.detail["has_structured_tool_calls"] as? Bool, false)
        XCTAssertEqual(ResponseVerify.stripPseudoToolMarkup(content), "I will list files.")
    }

    func testPseudoToolMarkupUnterminated() {
        let content = "oops " + tco + "\n{\"name\": \"ls\""
        let hit = ResponseVerify.pseudoToolCallInContent(.init(content: content))
        XCTAssertEqual(hit?.onset, 5)
        // Only the bare tag is removed; the JSON body stays (Python parity).
        XCTAssertEqual(ResponseVerify.stripPseudoToolMarkup(content), "oops \n{\"name\": \"ls\"")
    }

    func testPseudoToolMarkupCleanContent() {
        XCTAssertNil(ResponseVerify.pseudoToolCallInContent(
            .init(content: "plain answer without markup")))
    }

    // MARK: empty content + long reasoning

    func testEmptyContentLongReasoning() {
        let reasoning = String(repeating: "reasoning about the task. ", count: 40)
        let hit = ResponseVerify.emptyContentLongReasoning(
            .init(content: "", reasoningContent: reasoning))
        XCTAssertEqual(hit?.policyId, ResponseVerify.emptyLongReasoningId)
        XCTAssertEqual(hit?.kind, "empty_content_long_reasoning")
        XCTAssertEqual(hit?.onset, 400)
        XCTAssertEqual(hit?.detail["reasoning_len"] as? Int, 1040)
        // Short reasoning: no hit.
        XCTAssertNil(ResponseVerify.emptyContentLongReasoning(
            .init(content: "", reasoningContent: "short")))
    }

    // MARK: degenerate tool args

    private func call(_ name: String, _ args: String) -> OpenAIChatCompat.ToolCallSpec {
        OpenAIChatCompat.ToolCallSpec(id: "c1", name: name, arguments: args)
    }

    func testDegenerateWriteBadPath() {
        let hit = ResponseVerify.degenerateToolArgs(
            .init(toolCalls: [call("write", "{\"path\": \"Tower\", \"content\": \"0.5\"}")]))
        XCTAssertEqual(hit?.policyId, ResponseVerify.degenerateToolArgsId)
        XCTAssertEqual(hit?.kind, "degenerate_tool_args")
        XCTAssertEqual(hit?.field, "tool_calls")
        XCTAssertEqual(hit?.onset, 0)
        XCTAssertEqual(hit?.detail["tool"] as? String, "write")
        XCTAssertEqual(hit?.detail["reason"] as? String, "path_not_filelike")
        XCTAssertEqual(hit?.detail["path"] as? String, "Tower")
        XCTAssertEqual(hit?.detail["content_len"] as? Int, 3)
    }

    func testDegenerateWriteContentEqualsPath() {
        let hit = ResponseVerify.degenerateToolArgs(
            .init(toolCalls: [call("write", "{\"path\": \"README.md\", \"content\": \"README.md\"}")]))
        XCTAssertEqual(hit?.detail["reason"] as? String, "content_equals_path")
        XCTAssertEqual(hit?.detail["content_len"] as? Int, 9)
    }

    func testDegenerateWriteThinSourceEdge() {
        // 12-char .rs content is NOT flagged (evprtr parity: < 12 required).
        let hit = ResponseVerify.degenerateToolArgs(
            .init(toolCalls: [call("write", "{\"path\": \"main.rs\", \"content\": \"fn main() {}\"}")]))
        XCTAssertNil(hit)
    }

    func testDegenerateWriteHealthy() {
        let hit = ResponseVerify.degenerateToolArgs(
            .init(toolCalls: [call("write", "{\"path\": \"src/main.rs\", \"content\": \"fn main() { println!(\\\"ok\\\"); }\"}")]))
        XCTAssertNil(hit)
    }

    func testDegenerateEditNoop() {
        let hit = ResponseVerify.degenerateToolArgs(
            .init(toolCalls: [call("edit", "{\"path\": \"a.txt\", \"edits\": [{\"oldText\": \"same\", \"newText\": \"same\"}]}")]))
        XCTAssertEqual(hit?.detail["reason"] as? String, "noop_edit")
        XCTAssertEqual(hit?.detail["path"] as? String, "a.txt")
        XCTAssertEqual(hit?.detail["old_len"] as? Int, 4)
    }

    func testDegenerateEditEmpty() {
        let hit = ResponseVerify.degenerateToolArgs(
            .init(toolCalls: [call("edit", "{\"path\": \"a.txt\", \"edits\": []}")]))
        XCTAssertEqual(hit?.detail["reason"] as? String, "empty_edits")
    }

    func testDegenerateEditInventedOldText() {
        let hit = ResponseVerify.degenerateToolArgs(
            .init(toolCalls: [call("edit", "{\"path\": \"Cargo.toml\", \"edits\": [{\"oldText\": \"non-empty oldtext here\", \"newText\": \"x\"}]}")]))
        XCTAssertEqual(hit?.detail["reason"] as? String, "invented_old_text")
    }

    func testDegenerateEditHealthy() {
        let hit = ResponseVerify.degenerateToolArgs(
            .init(toolCalls: [call("edit", "{\"path\": \"src/main.rs\", \"edits\": [{\"oldText\": \"let x = 1;\", \"newText\": \"let x = 2;\"}]}")]))
        XCTAssertNil(hit)
    }

    func testDegenerateUnparsableArguments() {
        // Unparsable arguments -> empty args -> write path check fails.
        let hit = ResponseVerify.degenerateToolArgs(
            .init(toolCalls: [call("write", "not json")]))
        XCTAssertEqual(hit?.detail["reason"] as? String, "path_not_filelike")
    }

    // MARK: bundle order (pipeline parity)

    func testVerifyBundleOrderAndFirst() {
        // Repetition in content + markup leak: repetition first (bundle order).
        let messy = String(repeating: "tr", count: 20) + " more text here for length"
        let content = messy + "\n" + block("{}")
        let outcome = ResponseVerify.verify(.init(content: content))
        XCTAssertEqual(outcome.hits.first?.policyId, ResponseVerify.genericRepetitionId)
        XCTAssertTrue(outcome.hits.contains { $0.policyId == ResponseVerify.pseudoToolMarkupId })
        if let f = outcome.first, let h = outcome.hits.first {
            XCTAssertEqual(f.policyId, h.policyId)
            XCTAssertEqual(f.kind, h.kind)
            XCTAssertEqual(f.onset, h.onset)
        }
    }

    func testVerifyHealthyMessage() {
        let outcome = ResponseVerify.verify(
            .init(content: "A perfectly normal, complete, and useful answer to the user's question."))
        XCTAssertTrue(outcome.hits.isEmpty)
        XCTAssertNil(outcome.first)
    }

    // MARK: think interior

    func testThinkInterior() {
        let raw = "prose" + ResponseVerify.thinkOpen + "deep reasoning here" + ResponseVerify.thinkClose + "answer"
        XCTAssertEqual(ResponseVerify.thinkInterior(of: raw), "deep reasoning here")
        let unclosed = "x" + ResponseVerify.thinkOpen + "dangling"
        XCTAssertEqual(ResponseVerify.thinkInterior(of: unclosed), "dangling")
        XCTAssertNil(ResponseVerify.thinkInterior(of: "no block"))
    }
}